### ISSUE TITLE
Not work for Alfred 3.4.1 & osx 10.12.6 

### ISSUE THREAD

**Issue by KamisamaJin** [aviaryan/alfred-clc#1]
Debug console output:  /run.sh:13: command not found: insect
but I've installed insect,
so I tried to add this line:

`PATH=$($(echo $SHELL) -ic 'echo $PATH'):/usr/local/bin:$PATH`

it works.

**Comment by aviaryan** [comment]
Can you access `insect` from the bash shell normally? What about zsh?

**Comment by anandsinghs257** [comment]
Which prog are you learning?

**Comment by aviaryan** [comment]
Thank you @KamisamaJin. Explicitly adding `local/bin` in the PATH seems like a good idea and has no harm. I went ahead and pushed the patch under `master`. Workflow has been updated now. 👏 

@anandsinghs257 Apologies, I deleted your comment by mistake. Please check if the fix is working for you and revert back if any issues. I will be glad to assist you with it. (GitHub seriously needs to add a confirmation before they delete the message)
